"""add deadline and remind_via_email to tasks

Revision ID: 00e7569b9180
Revises: 376681b17238
Create Date: 2026-03-21 21:46:56.073460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00e7569b9180'
down_revision = '376681b17238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadline', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('remind_via_email', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('remind_via_email')
        batch_op.drop_column('deadline')

    # ### end Alembic commands ###
