"""Add lists module and task relation

Revision ID: 376681b17238
Revises: e051d08346a7
Create Date: 2026-03-20 19:52:22.519817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '376681b17238'
down_revision = 'e051d08346a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_lists_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lists'))
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('list_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_tasks_list_id_lists'), 'lists', ['list_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tasks_list_id_lists'), type_='foreignkey')
        batch_op.drop_column('list_id')

    op.drop_table('lists')
    # ### end Alembic commands ###
