"""add push notification fields

Revision ID: 8772e8103424
Revises: a09fec1a1fe9
Create Date: 2026-03-28 19:35:13.910858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8772e8103424'
down_revision = 'a09fec1a1fe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remind_via_push', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reminder_sent', sa.Boolean(), nullable=True))
        batch_op.drop_column('remind_via_email')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fcm_token', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('fcm_token')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remind_via_email', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('reminder_sent')
        batch_op.drop_column('remind_via_push')

    # ### end Alembic commands ###
